[workspace]
members = [
  "spritec-preview",
]

[package]
name = "spritec"
version = "0.1.0"
authors = [
  "Sunjay Varma <varma.sunjay@gmail.com>",
  "James Shi <jsjamesshi@gmail.com>",
  "Bill Chen <bchen.tcu@gmail.com>",
  "Mara Gagiu <mara.gagiu@gmail.com>",
]
edition = "2018"

[dependencies]
euc = "0.2"
tobj = "0.1"
vek = { version = "0.9", features = ["serde"] }
gltf = "0.14"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }

# Dependencies that don't support / shouldn't be used with WASM
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
structopt = "0.2"
image = "0.22"
rayon = "1.2"

[profile.dev]
# Needed to make software rendering fast enough
opt-level = 3
