# Configuration file for generating images with spritec
#
# Paths in this file are relative to the location of this configuration file

[[poses]]
model = "priest_000001.obj"
path = "../../priest000001.png"
width = 128
height = 128
scale = 6
camera = "PerspectiveFront"

[[poses]]
model = "priest_000001.obj"
path = "../../priest000002.png"
width = 128
height = 128
scale = 6
camera = "PerspectiveRight"
